### ISSUE TITLE
Move off of `lerna`

### ISSUE THREAD

**Issue by patrickdevivo** [mergestat/blocks-legacy#116]
Lerna is deprecated, https://turborepo.org/ seems exciting and interesting. Let's investigate switching over to that.

**Comment by amenowanna** [comment]
NX seems to be winning out on turborepo so for now this is what we are moving forward with in our testing and implementation.

**Comment by german-mergestat** [comment]
Here a kind of plan for this improvement:

- [X] Create NX `monorepo` project scaffolding.
- [X] Configure storybook with tailwind.
- [X] Migrate all components for `Icons`
- [x] Migrate all components for `blocks`
- [x] Ensure all styles stuffs working well, adjust things if necessary
- [x] Solve console errors with `tippyjs` lib (Try to solve or maybe try another lib for tooltips)
- [x] Publish a new version in `NPM` registry and test if all working well
- [ ] Review `Linting`, maybe configure some specific rules similar to `mergestat` project
- [x] Migrate CI file and test
- [ ] Review this workflow to automatically publish when a PR is approved https://storybook.js.org/tutorials/design-systems-for-developers/react/en/workflow/
- [x] Pass last sidebar changes from blocks to this blocks-next (collapsible feature)
- [ ] Handle the cutover from blocks to blocks-next (https://github.com/mergestat/internal/issues/114)
- [x] Make use of new `blocks` version in `mergestat` repo. https://github.com/mergestat/mergestat/pull/631
- [ ] Make a kind of architecture documentation in notion of new `blocks-next` repo.

**Comment by patrickdevivo** [comment]
sounds good to me!
